version: '3'
services:
  librarydb:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: librarydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge