version: '3'
services:
  libraryDb:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: librarydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3308:3308"